export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const START_FETCH_PRODUCTS = 'START_FETCH_PRODUCTS';
export const RECEIVE_FETCH_PRODUCTS = 'RECEIVE_FETCH_PRODUCTS';

export const LOAD_MORE_PRODUCTS = 'LOAD_MORE_PRODUCT';
export const START_LOAD_MORE_PRODUCTS = 'START_LOAD_MORE_PRODUCT';
export const RECEIVE_MORE_PRODUCTS = 'RECEIVE_MORE_PRODUCT';


export const FETCH_USERS = 'FETCH_USERS';
export const START_FETCH_USERS = 'START_FETCH_USERS';
export const RECEIVE_FETCH_USERS = 'RECEIVE_FETCH_USERS';

export const LOAD_MORE_USERS = 'LOAD_MORE_USERS';
export const START_LOAD_MORE_USERS = 'START_LOAD_MORE_USERS';
export const RECEIVE_MORE_USERS = 'RECEIVE_MORE_USERS';
